"""Initial migration

Revision ID: 7350c6d255e7
Revises: 
Create Date: 2024-08-06 01:33:09.730014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7350c6d255e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('ownership_type', sa.Integer(), nullable=True),
                    sa.Column('inn', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('company_id'),
                    sa.UniqueConstraint('inn')
                    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
